<a href="https://colab.research.google.com/github/Winlai16/MMDT_T-PY101_Batch03/blob/main/wlp_phyu/ex06_function_02/winlaiphyu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exercises cover both Exception Handling and variable scopes.
Q1) Run the following programs, identify and Fix the errors.
Use exception handling approach to handle the erros.

In [ ]:
#Q1.1) Zero division error
def myfunction(a,b):
    try:
      answer = a/b
      return answer
    except ZeroDivisionError:
      print ("Division by zero is mathematically not allowed")

#Call the function as follows:
myfunction(2,0)


Division by zero is mathematically not allowed


In [ ]:
#Q1.2 Name Error

def myfunction2(c):
  try:
    answer = a/c
    return answer
  except NameError:
    print("name is not founded")


# Call the function as follows:
myfunction2(3)

name is not founded


In [ ]:
#Q1.3 IndexError
def myfunction3(b):
  try:
    mylist = [2, 3, 5, -7, 8, 0]
    idx = 0
    while idx<=6:
        print('Iteration:', idx, mylist[idx]/b)
        idx = idx+1
        print('Iteration completed')
  except IndexError:
    print("Your index have error,try again")

# Call the function as follows:
myfunction3(b=5)

Iteration: 0 0.4
Iteration completed
Iteration: 1 0.6
Iteration completed
Iteration: 2 1.0
Iteration completed
Iteration: 3 -1.4
Iteration completed
Iteration: 4 1.6
Iteration completed
Iteration: 5 0.0
Iteration completed
Your index have error,try again


In [ ]:
#Q1.4 Zero Division Error, Value Error
def divide(a, b):
  try:
    result = a / b
    print('The result of division is', result)
    # FIX THE ERROR BELOW
    # ZeroDivisionError
    # ValueError
    return result
  except ZeroDivisionError:
    print ("Division by zero is mathematically not allowed")
  except TypeError:
    print("Data have value error and try agian")

# Call the function as follows:
divide("10",2)
divide(10,0)
divide(10, "two")

Data have value error and try agian
Division by zero is mathematically not allowed
Data have value error and try agian


In [ ]:
#Q1.5 FileNotFoundError
def read_file(filename):
  try:
    with open(filename, 'r') as file1:
        word_string = file1.read()
    print("File reading completed successfully")
    # FIX THE ERROR BELOW
    # FileNotFoundError
    return word_string
  except FileNotFoundError:
    print("Please check your file path and name")


# Call the function as follows:
read_file("Q1.txt")

Please check your file path and name


Q2) Run the following programs and fix the errors.
Check the scopes of the variable, and fix it.

In [ ]:
def check_rows(grid, expected_numbers):
    """Checks for uniqueness and completeness (1-9) in every row."""
    for i, row in enumerate(grid):
        if set(row) != expected_numbers:
            return False, f"Row {i + 1}: {row}"
    return True, None

def check_cols(grid, expected_numbers):
    """Checks for uniqueness and completeness (1-9) in every column."""
    sudoku_size = len(grid)
    for j in range(sudoku_size):
        column = [grid[i][j] for i in range(sudoku_size)]
        if set(column) != expected_numbers:
            return False, f"Column {j + 1}: {column}"
    return True, None

def check_blocks(grid, expected_numbers):
    """Checks for uniqueness and completeness (1-9) in every 3x3 block."""
    # Iterate over the starting indices for the 9 blocks: (0,0), (0,3), (0,6), (3,0), ...
    for block_row_start in [0, 3, 6]:
        for block_col_start in [0, 3, 6]:
            block = []

            # Extract the 3x3 block's elements
            for i in range(block_row_start, block_row_start + 3):
                for j in range(block_col_start, block_col_start + 3):
                    block.append(grid[i][j])

            # Check for uniqueness and completeness (1-9)
            if set(block) != expected_numbers:
                return False, f"Block at ({block_row_start+1}, {block_col_start+1})"
    return True, None

def is_sudoku_solved(grid):
    """
    Checks if the given 9x9 grid is a correctly solved Sudoku puzzle by verifying
    row, column, and 3x3 block constraints.
    """
    global sudoku_size
    sudoku_size = len(grid)
    # 1. Basic check: Ensure the grid is 9x9
    if len(grid) != 9 or any(len(row) != 9 for row in grid):
        print("Error: Grid must be exactly 9x9.")
        return False

    # The set of expected numbers for a solved unit (row, column, or block)
    expected_numbers = set(range(1, 10))

    # 2. Check Rows
    is_valid, error_info = check_rows(grid, expected_numbers)
    if not is_valid:
        print(f"Mistake found in {error_info}")
        return False

    # 3. Check Columns
    is_valid, error_info = check_cols(grid, expected_numbers)
    if not is_valid:
        print(f"Mistake found in {error_info}")
        return False

    # 4. Check Blocks
    is_valid, error_info = check_blocks(grid, expected_numbers)
    if not is_valid:
        print(f"Mistake found in {error_info}")
        return False

    # If all checks pass, the Sudoku is solved correctly
    return True

# calling the function as follows:

import numpy as np
grid = np.random.randint(1,10,(9,9))
print(grid)
is_sudoku_solved(grid.tolist())

solved_grid = [
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]]
is_sudoku_solved(solved_grid)

[[5 2 5 6 1 3 4 3 6]
 [3 9 1 8 2 5 2 5 1]
 [1 8 6 8 6 3 2 6 6]
 [3 2 5 3 8 8 6 6 7]
 [9 2 3 2 1 3 9 3 8]
 [9 4 3 1 4 8 3 8 8]
 [4 8 8 4 1 2 3 9 1]
 [6 7 5 9 6 2 8 9 9]
 [6 2 8 1 6 2 4 2 3]]
Mistake found in Row 1: [5, 2, 5, 6, 1, 3, 4, 3, 6]


True